name: Test laravel projects

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Test Laravel
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        coverage: none
        tools: composer:v2

    - name: Test Laravel
      run: |
        ./tests/laravel-test.sh

    - name: Test Lumen
      run: |
        ./tests/lumen-test.sh
